# Generated by Django 4.2 on 2023-08-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersite',
            name='permission_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersite',
            name='permission_user',
            field=models.BooleanField(default=False),
        ),
    ]
