# Generated by Django 4.2 on 2023-08-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usersite_permission_admin_usersite_permission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersite',
            name='permission_admin',
            field=models.BooleanField(default=False),
        ),
    ]
