# Generated by Django 4.2 on 2023-08-21 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_books_book_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
