# Generated by Django 4.2 on 2023-08-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_books_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/book-file/'),
        ),
    ]
