# Generated by Django 4.2 on 2023-08-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_book_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/book-file/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/book-img/'),
        ),
    ]
