# Generated by Django 4.2 on 2023-08-21 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_book_book_file_alter_book_book_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='NonFictionBook',
        ),
    ]
