# Generated by Django 4.2 on 2023-08-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_book_nonfictionbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonfictionbook',
            name='book_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
