# Generated by Django 4.2 on 2023-08-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_nonfictionbook_book_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonfictionbook',
            old_name='book_file',
            new_name='bookFile',
        ),
        migrations.RenameField(
            model_name='nonfictionbook',
            old_name='book_image',
            new_name='bookImage',
        ),
        migrations.AlterField(
            model_name='nonfictionbook',
            name='book_name',
            field=models.CharField(max_length=250),
        ),
    ]
