# Generated by Django 4.2 on 2023-08-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_book_file_nonfictionbook_bookfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonfictionbook',
            name='current_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nonfictionbook',
            name='last_page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
