# Generated by Django 4.2 on 2023-09-03 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_nonfictionbook_current_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_description', models.CharField(max_length=250)),
                ('completed', models.BooleanField(default=False)),
                ('due_date', models.DateField()),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usersite')),
            ],
        ),
    ]
