# Generated by Django 4.2 on 2023-09-11 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.BooleanField(default=False)),
                ('admin_role', models.BooleanField(default=False)),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usersite')),
            ],
        ),
    ]
