# Generated by Django 4.2 on 2023-09-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersite',
            name='permission_admin',
        ),
        migrations.RemoveField(
            model_name='usersite',
            name='permission_user',
        ),
    ]
