# Generated by Django 4.2 on 2023-09-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_usersite_permission_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonfictionbook',
            name='date_modified',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
