# Generated by Django 4.2 on 2023-09-17 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_nonfictionbook_date_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonficBooksUpdates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_ref', models.CharField(blank=True, max_length=250, null=True)),
                ('actions', models.CharField(max_length=250)),
                ('book_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nonfictionbook')),
            ],
        ),
    ]
