# Generated by Django 4.2 on 2023-09-17 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_nonficbooksupdates'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookUpdates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actions', models.CharField(max_length=250)),
                ('book_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nonfictionbook')),
            ],
        ),
        migrations.DeleteModel(
            name='NonficBooksUpdates',
        ),
    ]
