# Generated by Django 4.2 on 2023-09-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_bookupdates_bookupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookupdate',
            name='book_ref',
        ),
        migrations.AddField(
            model_name='bookupdate',
            name='book_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bookupdate',
            name='date_action_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bookupdate',
            name='user',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bookupdate',
            name='actions',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
