# Generated by Django 4.2 on 2023-09-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_bookupdate_book_ref_bookupdate_book_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoUpdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('actions', models.CharField(max_length=250)),
                ('date_action_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
