# Generated by Django 4.2 on 2023-10-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_todoupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisited',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_visited', models.DateField(auto_now_add=True)),
                ('number_visitor', models.IntegerField()),
            ],
        ),
    ]
