# Generated by Django 4.2 on 2023-10-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_sitevisited_date_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisited',
            name='date_visited',
            field=models.DateField(auto_created=True),
        ),
    ]
